fix fact error on systems without tw_cli
Fix the logic bug that caused this error on systems without a valid tw_controllers fact.

	Could not retrieve tw_controllers: unexpected return
	Error: private method `split' called for nil:NilClass